server:
  port: 3344

spring:
  application:
    name:  springcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/newFisherkk/springcloud-config.git #GitHub上面的git仓库名字
#如果用ssh地址会出现auth fail